name: validatietool

channels:
  - conda-forge
  - defaults

dependencies:
  - python<=3.9
  - black
  - geopandas<=0.10.2
  - jupyter
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - numpy
  - pandas<=1.5.3
  - pip
  - git
  - pytest
  - pytest-cov
  - rasterio=1.2.10
  - rasterstats<=0.16.0
  - rtree
  - spyder